repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.5' # Use a recent ruff version
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit]
    -   id: pytest-cov
        name: pytest-cov
        entry: pytest --cov=kolmogorov_complexity_estimator --cov-report=xml
        language: system
        types: [python]
        pass_filenames: false
        stages: [commit] 